#!/usr/bin/env python3

DNA = 'GATGGGATTggggttttccccTCCCATGTGCTCAAGACTGGCGCTaaaaGttttGAGCTTCTCaaaaGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCggggACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGccccCTCTGAGTCAGGAAACAttttCAGACCTATGGAAACTACTTCCTGaaaaCAACGTTCTGTccccCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTccccGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTccccCCGTGGccccTGCACCAGCAGCTCCTACACCGGCGGccccTGCACCAGccccCTCCTGGccccTGTCATCTTCTGTCCCTTCCCAGaaaaCCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTccccTGCCCTCAACAAGATGttttGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACAccccCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGccccCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGccccTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACttttCG'
print(DNA.count('A'))
print(DNA.count('a'))
print('test',DNA.count('A')+DNA.count('a'))
DNA1 = DNA.upper()
#creating a new variable where all letters are uppercase
print(DNA1)
print(DNA1.count('A'))
print(DNA1.count('a'))
#replace all T's woth U's
RNA = DNA1.replace('T','U')
print(RNA)

#count AT content
print('AT content =',((DNA1.count('A') + DNA1.count('T'))/len(DNA1))*100)
print('GC content =',((DNA1.count('G') + DNA1.count('C'))/len(DNA1))*100)
sub_DNA1 = DNA1[101:201]
print('sub_DNA1',sub_DNA1)
print('AT content =',((sub_DNA1.count('A') +sub_DNA1.count('T'))/len(sub_DNA1))*100)
print('GC content =',((sub_DNA1.count('G') +sub_DNA1.count('C'))/len(sub_DNA1))*100)

